services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable_freqai
    restart: unless-stopped
    container_name: crypto-quant-lab-freqtrade
    volumes:
      - ./user_data:/freqtrade/user_data
    ports:
      - "127.0.0.1:8080:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/configs/config.dryrun.json
      --config /freqtrade/user_data/configs/config.freqai.json
      --config /freqtrade/user_data/configs/config.private.json
      --strategy ScalpingFreqaiStrategy
      --freqaimodel LightGBMRegressor
